--- #YAML:1.0
name: CGI-FileManager
version: 0.04
author:
  - Gabor Szabo <gabor@pti.co.il>
abstract: Managing a directory structure on an HTTP server
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
